# -*- coding: utf-8 -*-
"""chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FsRSXhvcs1Ynhjqu0wP_oC8YgvAorpn
"""

# Simple Chatbot using Rule-Based Responses

def chatbot_response(user_input):
    user_input = user_input.lower()  # Make input lowercase for matching
    if "hello" in user_input:
        return "Hi there! How can I assist you?"
    elif "how are you" in user_input:
        return "I'm a bot, but I'm functioning properly. Thank you!"
    elif "help" in user_input:
        return "Sure! Tell me what you need help with."
    elif "bye" in user_input:
        return "Goodbye! Have a nice day!"
    else:
        return "Sorry, I didn't understand that. Try saying hello or help."

# Example conversation (Google Colab cannot use input())
print("Example Test:")
print("You: hello")
print("Chatbot:", chatbot_response("hello"))

print("\nYou: how are you")
print("Chatbot:", chatbot_response("how are you"))

print("\nYou: help")
print("Chatbot:", chatbot_response("help"))

print("\nYou: bye")
print("Chatbot:", chatbot_response("bye"))

print("\nYou: unknown text")
print("Chatbot:", chatbot_response("I want pizza"))